import type { OxlintConfig } from 'oxlint'

import type {
  OptionsFiles,
  OptionsOverrides,
  OptionsProjectType,
  OptionsTypeScriptParserOptions,
  OptionsTypeScriptWithTypes,
} from '../types.ts'

import { GLOB_TS, GLOB_TSX } from '../globs.ts'

export function typescript(
  options: OptionsFiles &
    OptionsOverrides &
    OptionsProjectType &
    OptionsTypeScriptParserOptions &
    OptionsTypeScriptWithTypes = {},
): OxlintConfig {
  const {
    files = [GLOB_TS, GLOB_TSX],
    filesTypeAware = [GLOB_TS, GLOB_TSX],
    ignoresTypeAware = [],
    overrides = {},
    overridesTypeAware = {},
    tsconfigPath,
    type = 'app',
  } = options

  const isTypeAware = !!tsconfigPath

  const typeAwareRules: OxlintConfig['rules'] = {
    'constructor-super': 'off',
    'getter-return': 'off',
    'no-class-assign': 'off',
    'no-const-assign': 'off',
    'no-dupe-keys': 'off',
    'no-func-assign': 'off',
    'no-implied-eval': 'off',
    'no-new-native-nonconstructor': 'off',
    'no-obj-calls': 'off',
    'no-setter-return': 'off',
    'no-this-before-super': 'off',
    'no-throw-literal': 'off',
    'no-undef': 'off',
    'no-unreachable': 'off',
    'no-unsafe-negation': 'off',
    'no-with': 'off',
    'prefer-promise-reject-errors': 'off',
    'require-await': 'off',

    'typescript/await-thenable': 'error',
    'typescript/consistent-return': 'off',
    'typescript/consistent-type-exports': 'error',
    'typescript/dot-notation': ['error', { allowKeywords: true }],
    'typescript/no-array-delete': 'error',
    'typescript/no-base-to-string': 'error',
    'typescript/no-confusing-void-expression': ['error', { ignoreArrowShorthand: true }],
    'typescript/no-deprecated': 'warn',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    'typescript/no-meaningless-void-operator': 'warn',
    'typescript/no-misused-promises': 'error',
    'typescript/no-misused-spread': 'error',
    'typescript/no-mixed-enums': 'error',
    'typescript/no-redundant-type-constituents': 'error',
    'typescript/no-unnecessary-boolean-literal-compare': 'error',
    'typescript/no-unnecessary-condition': 'off', // TBD
    'typescript/no-unnecessary-qualifier': 'warn',
    'typescript/no-unnecessary-template-expression': 'warn',
    'typescript/no-unnecessary-type-arguments': 'warn',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-conversion': 'warn',
    'typescript/no-unnecessary-type-parameters': 'warn',
    'typescript/no-unsafe-argument': 'error',
    'typescript/no-unsafe-assignment': 'error',
    'typescript/no-unsafe-call': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-return': 'error',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/no-unsafe-unary-minus': 'error',
    'typescript/no-useless-default-assignment': 'warn',
    'typescript/non-nullable-type-assertion-style': 'warn',
    'typescript/only-throw-error': ['error', { allowThrowingAny: false }],
    'typescript/prefer-find': 'warn',
    'typescript/prefer-includes': 'warn',
    'typescript/prefer-nullish-coalescing': ['error', { ignorePrimitives: true }], // { ignoreConditionalTests: false },
    'typescript/prefer-optional-chain': 'error',
    'typescript/prefer-promise-reject-errors': 'error',
    'typescript/prefer-readonly': 'warn',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/prefer-reduce-type-parameter': 'error',
    'typescript/prefer-regexp-exec': 'warn',
    'typescript/prefer-return-this-type': 'warn',
    'typescript/prefer-string-starts-ends-with': 'warn',
    'typescript/promise-function-async': 'error',
    'typescript/related-getter-setter-pairs': 'error',
    'typescript/require-array-sort-compare': ['error', { ignoreStringArrays: true }],
    'typescript/require-await': 'off', // TBD
    'typescript/restrict-plus-operands': [
      'error',
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
      },
    ],
    'typescript/restrict-template-expressions': [
      'error',
      {
        allowAny: false,
        allowBoolean: false,
        allowNever: false,
        allowNullish: false,
        allowNumber: true,
        allowRegExp: false,
      },
    ],
    'typescript/return-await': ['error', 'in-try-catch'],
    'typescript/strict-boolean-expressions': [
      'error',
      { allowNullableBoolean: true, allowNullableObject: true },
    ],
    'typescript/strict-void-return': 'error',
    'typescript/switch-exhaustiveness-check': [
      'error',
      {
        considerDefaultExhaustiveForUnions: true,
        requireDefaultForNonUnion: true,
      },
    ],
    'typescript/unbound-method': 'error',
    'typescript/use-unknown-in-catch-callback-variable': 'error',
  }

  return {
    options: {
      typeAware: isTypeAware,
    },
    plugins: ['typescript'],
    overrides: [
      {
        files,
        rules: {
          'typescript/adjacent-overload-signatures': 'error',
          'typescript/array-type': 'error',
          'typescript/await-thenable': 'off',
          'typescript/ban-ts-comment': ['error', { 'ts-expect-error': 'allow-with-description' }],
          'typescript/ban-tslint-comment': 'off',
          'typescript/class-literal-property-style': ['error', 'fields'],
          'typescript/consistent-generic-constructors': ['error', 'constructor'],
          'typescript/consistent-indexed-object-style': ['error', 'record'],
          'typescript/consistent-return': 'off',
          'typescript/consistent-type-assertions': [
            'error',
            { assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' },
          ],
          'typescript/consistent-type-definitions': ['error', 'interface'],
          'typescript/consistent-type-exports': 'off',
          'typescript/consistent-type-imports': [
            'error',
            {
              disallowTypeAnnotations: false,
              fixStyle: 'separate-type-imports',
              prefer: 'type-imports',
            },
          ],
          'typescript/dot-notation': 'off',
          'typescript/explicit-function-return-type': 'off',
          'typescript/explicit-member-accessibility': ['error', { accessibility: 'no-public' }],
          'typescript/explicit-module-boundary-types': 'off',
          'typescript/method-signature-style': ['error', 'property'],
          'typescript/no-array-delete': 'off',
          'typescript/no-base-to-string': 'off',
          'typescript/no-confusing-non-null-assertion': 'error',
          'typescript/no-confusing-void-expression': 'off',
          'typescript/no-deprecated': 'off',
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-duplicate-type-constituents': 'off',
          'typescript/no-dynamic-delete': 'error',
          'typescript/no-empty-object-type': ['error', { allowInterfaces: 'always' }],
          'typescript/no-explicit-any': 'off',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-extraneous-class': 'warn',
          'typescript/no-floating-promises': 'off',
          'typescript/no-for-in-array': 'off',
          'typescript/no-implied-eval': 'off',
          'typescript/no-import-type-side-effects': 'error',
          'typescript/no-inferrable-types': 'warn',
          'typescript/no-invalid-void-type': 'error',
          'typescript/no-meaningless-void-operator': 'off',
          'typescript/no-misused-new': 'error',
          'typescript/no-misused-promises': 'off',
          'typescript/no-misused-spread': 'off',
          'typescript/no-mixed-enums': 'off',
          'typescript/no-namespace': ['error', { allowDeclarations: true }],
          'typescript/no-non-null-asserted-nullish-coalescing': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-non-null-assertion': 'off',
          'typescript/no-redundant-type-constituents': 'off',
          'typescript/no-require-imports': 'error',
          'typescript/no-restricted-types': [
            'error',
            {
              types: {
                object: {
                  message:
                    'The `object` type is hard to use. Use `Record<string, unknown>` instead. See: https://github.com/typescript-eslint/typescript-eslint/pull/848',
                  fixWith: 'Record<string, unknown>',
                },
                '[]': "Don't use the empty array type `[]`. It only allows empty arrays. Use `SomeType[]` instead.",
              },
            },
          ],
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-boolean-literal-compare': 'off',
          'typescript/no-unnecessary-condition': 'off',
          'typescript/no-unnecessary-parameter-property-assignment': 'warn',
          'typescript/no-unnecessary-qualifier': 'off',
          'typescript/no-unnecessary-template-expression': 'off',
          'typescript/no-unnecessary-type-arguments': 'off',
          'typescript/no-unnecessary-type-assertion': 'off',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unnecessary-type-conversion': 'off',
          'typescript/no-unnecessary-type-parameters': 'off',
          'typescript/no-unsafe-argument': 'off',
          'typescript/no-unsafe-assignment': 'off',
          'typescript/no-unsafe-call': 'off',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-enum-comparison': 'off',
          'typescript/no-unsafe-function-type': 'error',
          'typescript/no-unsafe-member-access': 'off',
          'typescript/no-unsafe-return': 'off',
          'typescript/no-unsafe-type-assertion': 'off',
          'typescript/no-unsafe-unary-minus': 'off',
          'typescript/no-useless-default-assignment': 'off',
          'typescript/no-useless-empty-export': 'error',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/non-nullable-type-assertion-style': 'off',
          'typescript/only-throw-error': 'off',
          'typescript/parameter-properties': ['error', { prefer: 'class-property' }],
          'typescript/prefer-as-const': 'error',
          'typescript/prefer-enum-initializers': 'error',
          'typescript/prefer-find': 'off',
          'typescript/prefer-for-of': 'warn',
          'typescript/prefer-function-type': 'warn',
          'typescript/prefer-includes': 'off',
          'typescript/prefer-literal-enum-member': 'error',
          'typescript/prefer-namespace-keyword': 'off',
          'typescript/prefer-nullish-coalescing': 'off',
          'typescript/prefer-optional-chain': 'off',
          'typescript/prefer-promise-reject-errors': 'off',
          'typescript/prefer-readonly': 'off',
          'typescript/prefer-readonly-parameter-types': 'off',
          'typescript/prefer-reduce-type-parameter': 'off',
          'typescript/prefer-regexp-exec': 'off',
          'typescript/prefer-return-this-type': 'off',
          'typescript/prefer-string-starts-ends-with': 'off',
          'typescript/promise-function-async': 'off',
          'typescript/related-getter-setter-pairs': 'off',
          'typescript/require-array-sort-compare': 'off',
          'typescript/require-await': 'off',
          'typescript/restrict-plus-operands': 'off',
          'typescript/restrict-template-expressions': 'off',
          'typescript/return-await': 'off',
          'typescript/strict-boolean-expressions': 'off',
          'typescript/strict-void-return': 'off',
          'typescript/switch-exhaustiveness-check': 'off',
          'typescript/triple-slash-reference': 'off',
          'typescript/unbound-method': 'off',
          'typescript/unified-signatures': 'error',
          'typescript/use-unknown-in-catch-callback-variable': 'off',

          ...(type === 'lib'
            ? {
                'typescript/explicit-function-return-type': [
                  'error',
                  {
                    allowExpressions: true,
                    allowHigherOrderFunctions: true,
                    allowIIFEs: true,
                  },
                ],
              }
            : {}),

          ...overrides,
        },
      },
      ...(isTypeAware
        ? [
            {
              files: filesTypeAware,
              excludeFiles: ignoresTypeAware,
              rules: {
                ...typeAwareRules,
                ...overridesTypeAware,
              },
            },
          ]
        : []),
    ],
  }
}
