import type { OxlintConfig } from 'oxlint'

import type {
  OptionsFiles,
  OptionsOverrides,
  OptionsTypeScriptParserOptions,
  OptionsTypeScriptWithTypes,
} from '../types.ts'

import { GLOB_SRC, GLOB_TS, GLOB_TSX } from '../globs.ts'

export function unicorn(
  options: OptionsFiles &
    OptionsOverrides &
    OptionsTypeScriptParserOptions &
    OptionsTypeScriptWithTypes = {},
): OxlintConfig {
  const {
    files = [GLOB_SRC],
    filesTypeAware = [GLOB_TS, GLOB_TSX],
    ignoresTypeAware = [],
    overrides = {},
    tsconfigPath,
  } = options

  const isTypeAware = !!tsconfigPath

  const typeAwareRules: OxlintConfig['rules'] = {
    'unicorn/prefer-includes': 'off',
    'unicorn/prefer-string-starts-ends-with': 'off',
  }

  return {
    plugins: ['unicorn'],
    overrides: [
      {
        files,
        rules: {
          'unicorn/catch-error-name': 'error',
          'unicorn/consistent-assert': 'error',
          'unicorn/consistent-date-clone': 'error',
          'unicorn/consistent-empty-array-spread': 'error',
          'unicorn/consistent-existence-index-check': 'error',
          'unicorn/consistent-function-scoping': 'error',
          'unicorn/consistent-template-literal-escape': 'error',
          'unicorn/custom-error-definition': 'error',
          'unicorn/empty-brace-spaces': 'error',
          'unicorn/error-message': 'error',
          'unicorn/escape-case': 'error',
          'unicorn/explicit-length-check': 'error',
          'unicorn/explicit-timer-delay': 'error',
          'unicorn/filename-case': ['error', { cases: { kebabCase: true } }],
          'unicorn/import-style': 'error',
          'unicorn/max-nested-calls': 'off',
          'unicorn/new-for-builtins': 'error',
          'unicorn/no-abusive-eslint-disable': 'error',
          'unicorn/no-accessor-recursion': 'error',
          'unicorn/no-anonymous-default-export': 'off',
          'unicorn/no-array-callback-reference': 'error',
          'unicorn/no-array-fill-with-reference-type': 'error',
          'unicorn/no-array-for-each': 'error',
          'unicorn/no-array-method-this-argument': 'error',
          'unicorn/no-array-reduce': 'error',
          'unicorn/no-array-reverse': 'error',
          'unicorn/no-array-sort': 'off',
          'unicorn/no-await-expression-member': 'error',
          'unicorn/no-await-in-promise-methods': 'error',
          'unicorn/no-confusing-array-with': 'error',
          'unicorn/no-console-spaces': 'error',
          'unicorn/no-document-cookie': 'error',
          'unicorn/no-empty-file': 'error',
          'unicorn/no-hex-escape': 'off',
          'unicorn/no-immediate-mutation': 'error',
          'unicorn/no-instanceof-array': 'error',
          'unicorn/no-instanceof-builtins': 'error',
          'unicorn/no-invalid-fetch-options': 'error',
          'unicorn/no-invalid-remove-event-listener': 'error',
          'unicorn/no-length-as-slice-end': 'error',
          'unicorn/no-lonely-if': 'error',
          'unicorn/no-magic-array-flat-depth': 'error',
          'unicorn/no-negated-condition': 'off',
          'unicorn/no-negation-in-equality-check': 'error',
          'unicorn/no-nested-ternary': 'error',
          'unicorn/no-new-array': 'error',
          'unicorn/no-new-buffer': 'error',
          'unicorn/no-null': 'off',
          'unicorn/no-object-as-default-parameter': 'error',
          'unicorn/no-process-exit': 'error',
          'unicorn/no-single-promise-in-promise-methods': 'error',
          'unicorn/no-static-only-class': 'error',
          'unicorn/no-thenable': 'error',
          'unicorn/no-this-assignment': 'error',
          'unicorn/no-typeof-undefined': 'error',
          'unicorn/no-unnecessary-array-flat-depth': 'error',
          'unicorn/no-unnecessary-array-splice-count': 'error',
          'unicorn/no-unnecessary-await': 'error',
          'unicorn/no-unnecessary-slice-end': 'error',
          'unicorn/no-unreadable-array-destructuring': 'error',
          'unicorn/no-unreadable-iife': 'error',
          'unicorn/no-useless-collection-argument': 'error',
          'unicorn/no-useless-error-capture-stack-trace': 'error',
          'unicorn/no-useless-fallback-in-spread': 'error',
          'unicorn/no-useless-iterator-to-array': 'error',
          'unicorn/no-useless-length-check': 'error',
          'unicorn/no-useless-promise-resolve-reject': 'error',
          'unicorn/no-useless-spread': 'error',
          'unicorn/no-useless-switch-case': 'off',
          'unicorn/no-useless-undefined': 'off',
          'unicorn/no-zero-fractions': 'error',
          'unicorn/number-literal-case': 'off',
          'unicorn/numeric-separators-style': 'error',
          'unicorn/prefer-add-event-listener': 'error',
          'unicorn/prefer-array-find': 'error',
          'unicorn/prefer-array-flat': 'error',
          'unicorn/prefer-array-flat-map': 'error',
          'unicorn/prefer-array-index-of': 'error',
          'unicorn/prefer-array-some': 'error',
          'unicorn/prefer-at': 'error',
          'unicorn/prefer-bigint-literals': 'error',
          'unicorn/prefer-blob-reading-methods': 'error',
          'unicorn/prefer-class-fields': 'error',
          'unicorn/prefer-classlist-toggle': 'error',
          'unicorn/prefer-code-point': 'error',
          'unicorn/prefer-date-now': 'error',
          'unicorn/prefer-default-parameters': 'error',
          'unicorn/prefer-dom-node-append': 'error',
          'unicorn/prefer-dom-node-dataset': 'off',
          'unicorn/prefer-dom-node-remove': 'error',
          'unicorn/prefer-dom-node-text-content': 'error',
          'unicorn/prefer-event-target': 'error',
          'unicorn/prefer-export-from': ['error', { checkUsedVariables: false }],
          'unicorn/prefer-global-this': 'error',
          'unicorn/prefer-import-meta-properties': 'error',
          'unicorn/prefer-includes': 'error',
          'unicorn/prefer-keyboard-event-key': 'error',
          'unicorn/prefer-logical-operator-over-ternary': 'error',
          'unicorn/prefer-math-min-max': 'error',
          'unicorn/prefer-math-trunc': 'error',
          'unicorn/prefer-modern-dom-apis': 'error',
          'unicorn/prefer-modern-math-apis': 'error',
          'unicorn/prefer-module': 'error',
          'unicorn/prefer-native-coercion-functions': 'error',
          'unicorn/prefer-negative-index': 'error',
          'unicorn/prefer-node-protocol': 'error',
          'unicorn/prefer-number-coercion': 'off',
          'unicorn/prefer-number-properties': 'error',
          'unicorn/prefer-object-from-entries': 'error',
          'unicorn/prefer-optional-catch-binding': 'error',
          'unicorn/prefer-prototype-methods': 'error',
          'unicorn/prefer-query-selector': 'error',
          'unicorn/prefer-reflect-apply': 'error',
          'unicorn/prefer-regexp-test': 'error',
          'unicorn/prefer-response-static-json': 'error',
          'unicorn/prefer-set-has': 'error',
          'unicorn/prefer-set-size': 'error',
          'unicorn/prefer-single-call': 'error',
          'unicorn/prefer-spread': 'error',
          'unicorn/prefer-string-raw': 'error',
          'unicorn/prefer-string-replace-all': 'error',
          'unicorn/prefer-string-slice': 'error',
          'unicorn/prefer-string-starts-ends-with': 'error',
          'unicorn/prefer-string-trim-start-end': 'error',
          'unicorn/prefer-structured-clone': 'error',
          'unicorn/prefer-ternary': ['error', 'only-single-line'],
          'unicorn/prefer-top-level-await': 'error',
          'unicorn/prefer-type-error': 'error',
          'unicorn/relative-url-style': 'error',
          'unicorn/require-array-join-separator': 'error',
          'unicorn/require-module-attributes': 'error',
          'unicorn/require-module-specifiers': 'error',
          'unicorn/require-number-to-fixed-digits-argument': 'error',
          'unicorn/require-post-message-target-origin': 'error',
          'unicorn/switch-case-braces': ['error', 'always'],
          'unicorn/switch-case-break-position': 'error',
          'unicorn/text-encoding-identifier-case': 'error',
          'unicorn/throw-new-error': 'error',

          ...overrides,
        },
      },
      ...(isTypeAware
        ? [
            {
              files: filesTypeAware,
              excludeFiles: ignoresTypeAware,
              rules: {
                ...typeAwareRules,
              },
            },
          ]
        : []),
    ],
  }
}
